### ISSUE TITLE
Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by Fraer** [lunatech-labs/lunatech-scala-anonymization#1]
When running this command from the projects dir:
`sbt "run --input images/input --output images/output"`
I get:

```
[error] (run-main-0) com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
[error] com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
[error] 	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
[error] 	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:551)
[error] 	at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:305)
[error] 	at org.tensorflow.framework.GraphDef.<init>(GraphDef.java:52)
[error] 	at org.tensorflow.framework.GraphDef.<init>(GraphDef.java:13)
[error] 	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1543)
[error] 	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1538)
[error] 	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
[error] 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:239)
[error] 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:244)
[error] 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
[error] 	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:311)
[error] 	at org.tensorflow.framework.GraphDef.parseFrom(GraphDef.java:454)
[error] 	at nl.lunatech.anonymization.Detector.<init>(Detector.scala:25)
[error] 	at nl.lunatech.anonymization.Main$.delayedEndpoint$nl$lunatech$anonymization$Main$1(Main.scala:63)
[error] 	at nl.lunatech.anonymization.Main$delayedInit$body.apply(Main.scala:6)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at nl.lunatech.anonymization.Main$.main(Main.scala:6)
[error] 	at nl.lunatech.anonymization.Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 3 s, completed Jun 18, 2019 2:57:18 PM
```

**Comment by Fraer** [comment]
I'm on mac os 10.14.2 and i already installed protobuf
```
brew install protobuf
```
But i get the same error :(

**Comment by VincentBrule** [comment]
The problem comes from the models. 
Due to their weight, they are stored using git lfs.

To solve the problem, please follows the **first prerequisite in the updated README**.
